version: "3.7"

services:
    node:
        image: node:12-alpine
        container_name: neat-strapi
        working_dir: /app
        restart: always
        ports:
            - "3334:1337"
        volumes:
            - ./:/app
        user: ${CURRENT_UID}
            
            
networks:
    default:
        external: true
        name: neat-network