dev:
	docker-compose run --name neat-strapi --rm --service-ports node npm run develop

install:
	docker-compose run --rm node npm install

exec-node:
	docker-compose run --rm --entrypoint="/bin/sh" node