version: "3.7"

services:
    node:
        image: node:12-alpine
        container_name: neat-nuxt
        working_dir: /app
        restart: always
        ports:
            - "3333:8080"
        volumes:
            - ./app:/app
        user: ${CURRENT_UID}
            
            
networks:
    default:
        external: true
        name: neat-network